import type { ModelDebugLogger } from "./ModelDebugLogger";
import type { ModelClient, ModelEvent, ModelRequest } from "./ModelClient";
import { createReadFileToolCalls, findLastUserMessage, hasToolResultMessages, shouldReadContextFiles, streamText } from "./contextTooling";

const STREAM_DELAY_MS = 55;

export class FakeModelClient implements ModelClient {
  constructor(private readonly debugLogger?: ModelDebugLogger) {}

  async *stream(request: ModelRequest): AsyncIterable<ModelEvent> {
    this.debugLogger?.log("Fake model request", {
      provider: "fake",
      sessionId: request.sessionId,
      inputId: request.inputId,
      messages: request.messages,
      tools: request.tools,
      contextFiles: request.contextFiles
    });

    const userPrompt = findLastUserMessage(request);
    const toolResults = request.messages.filter((message) => message.role === "tool");

    if (isCompactionRequest(request)) {
      const response = formatFakeCompactionSummary(userPrompt);
      this.debugLogger?.log("Fake model response", {
        text: response
      });
      yield* streamText(response, request.signal, 16, 5);
      return;
    }

    if (isSessionNameRequest(request)) {
      const response = JSON.stringify({
        title: "Fake Agent Task",
        summary: findLastUserMessage(request).replace(/\s+/g, " ").trim().slice(0, 160)
      });
      this.debugLogger?.log("Fake model response", {
        text: response
      });
      yield* streamText(response, request.signal, 16, 5);
      return;
    }

    if (hasToolResultMessages(request)) {
      const response = formatToolResultAnswer(toolResults);
      this.debugLogger?.log("Fake model response", {
        text: response
      });
      yield* streamText(response, request.signal);
      return;
    }

    const mutationToolCall = parseExplicitToolCall(userPrompt);

    if (mutationToolCall) {
      this.debugLogger?.log("Fake model response", {
        toolCalls: [mutationToolCall]
      });
      yield mutationToolCall;
      yield {
        type: "finish",
        reason: "stop"
      };
      return;
    }

    if (shouldReadContextFiles(request)) {
      for (const toolCall of createReadFileToolCalls(request)) {
        this.debugLogger?.log("Fake model response", {
          toolCalls: [toolCall]
        });
        yield toolCall;
      }

      yield {
        type: "finish",
        reason: "stop"
      };
      return;
    }

    const response = [
      "Fake agent loop started.\n\n",
      `I can see ${Math.max(0, request.messages.length - 1)} prior message${request.messages.length - 1 === 1 ? "" : "s"} in this session before the current prompt.\n\n`,
      "This response is intentionally longer and chunked into small deltas so the webview can prove that streaming is real. ",
      "The current runtime is already following the same path a real coding model will use later: the prompt enters the durable session inbox, ",
      "the service promotes it at a safe boundary, the runner starts a provider turn, the model client emits deltas, and each delta is appended to the event log before the UI receives it.\n\n",
      "Your request was:\n\n",
      userPrompt,
      "\n\n",
      "Next milestones will replace this fake client with tool calls, read-only workspace tools, and then real model adapters. For now, this long fake answer exists to make timing, cancellation, and event replay visible."
    ].join("");

    this.debugLogger?.log("Fake model response", {
      text: response
    });
    yield* streamText(response, request.signal, 4, STREAM_DELAY_MS);
  }
}

function isCompactionRequest(request: ModelRequest) {
  return request.messages.some(
    (message) => message.role === "system" && message.content.includes("coding-agent session compactor")
  );
}

function isSessionNameRequest(request: ModelRequest) {
  return request.messages.some(
    (message) => message.role === "system" && message.content.includes("session metadata")
  );
}

function formatFakeCompactionSummary(prompt: string) {
  const transcriptStart = prompt.indexOf("# New Older Transcript Segment To Merge");
  const transcript = transcriptStart >= 0 ? prompt.slice(transcriptStart) : prompt;
  const preview = transcript.replace(/\s+/g, " ").trim().slice(0, 1_200);

  return [
    "## Goal",
    "- Continue the current coding-agent session using compacted prior context.",
    "",
    "## Constraints & Preferences",
    "- Preserve user requirements, file paths, provider/model decisions, errors, and milestone status.",
    "",
    "## Progress So Far",
    `- Fake compactor summarized older transcript segment: ${preview}`,
    "",
    "## Key Decisions / Facts",
    "- This summary was generated by FakeModelClient for deterministic local testing.",
    "",
    "## Relevant Files",
    "- (none extracted by fake compactor)",
    "",
    "## Blockers / Open Questions",
    "- Validate model-generated compaction with a real provider."
  ].join("\n");
}

function parseExplicitToolCall(prompt: string): ModelEvent | undefined {
  const match = /\b(write_file|edit_file|apply_patch|run_command|bash)\s+({[\s\S]*})\s*$/i.exec(prompt.trim());

  if (!match) {
    return undefined;
  }

  try {
    return {
      type: "tool_call",
      id: `fake_${match[1]}_${Date.now()}`,
      name: match[1].toLowerCase(),
      input: JSON.parse(match[2])
    };
  } catch {
    return undefined;
  }
}

function formatToolResultAnswer(toolResults: ModelRequest["messages"]) {
  const files = toolResults.map((message) => parseToolMessage(message.content));

  if (files.some((file) => file.tool !== "read_file")) {
    return [
      `I received ${files.length} tool result${files.length === 1 ? "" : "s"}.\n`,
      ...files.map((file, index) => {
        return [`\nTool ${index + 1}: ${file.tool}`, "```text", file.content, "```"].join("\n");
      })
    ].join("\n");
  }

  const lines = [`I read ${files.length} file${files.length === 1 ? "" : "s"}.\n`];

  files.forEach((file, index) => {
    lines.push(`\nFile ${index + 1}: ${file.path}\n`);
    lines.push("```text\n");
    lines.push(file.content);
    if (!file.content.endsWith("\n")) {
      lines.push("\n");
    }
    lines.push("```\n");
  });

  return lines.join("");
}

function parseToolMessage(content: string) {
  try {
    const parsed = JSON.parse(content) as { tool?: unknown; path?: unknown; content?: unknown };

    return {
      tool: typeof parsed.tool === "string" ? parsed.tool : "unknown",
      path: typeof parsed.path === "string" ? parsed.path : "unknown",
      content: typeof parsed.content === "string" ? parsed.content : content
    };
  } catch {
    return {
      tool: "unknown",
      path: "unknown",
      content
    };
  }
}
